name: Deploy Svelte to GitHub Pages

on:
  push:
    branches-ignore: [ 'master' ]

env:
  output-branch: pages
  output-dir: public
  commit-message: (*・∀-)ｂ update
  remote: https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Svelte
        run: |
          npm install
          npm run build

      - name: Deploy to Github Pages
        run: |
          echo ${{ env.remote }}
          cd ${{ env.output-dir }}
          git init
          git config --global user.email "support+actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add origin ${{ env.remote }}
          git checkout -b ${{ env.output-branch }}
          git add .
          git commit -m "${{ env.commit-message }}""
          git push -u origin github-pages -f

